### ISSUE TITLE
Implement http interface

### ISSUE THREAD

**Issue by jordi133** [scala-academy/akka-crashcourse#14]
Modify the current Webserver and http endpoints so that it can handle the following:
- POST to /games: create a new game and return the id
- GET to .games/<id>: returns the winner of that game

Tests for this story should include:
- Logic that isolates the path/route implementation and verifies that the logic directly behind the endpoints is correct
- An integration tests that actually starts the webserver and verifies that the endpoints are implemented correctly (combining as much of the GameManager/Game/Player logic as is available, fully integrating the application)

**Comment by jluijs** [comment]
Created some stuff, but waiting for gamemanager to complete so I can build it on that instead of building it on gameactor
